"""Apply research recommendations to live scoring and strategy routing.

This layer converts offline research output into small deterministic trading
adjustments. It stays intentionally conservative: no model fitting, just
threshold, session, and strategy-family guidance derived from the report files.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from trading_robot.types.enums import StrategyType


REVERSAL_PATTERNS = {"expansion_reversal", "sweep_reversal", "outside_bar_reversal", "doji"}
BREAKOUT_PATTERNS = {"expansion_continuation", "inside_bar_breakout"}


@dataclass(frozen=True)
class SymbolResearchTuning:
    """Per-symbol tuning hints generated by the research workflow."""

    preferred_sessions: tuple[str, ...] = ()
    avoided_sessions: tuple[str, ...] = ()
    preferred_patterns: tuple[str, ...] = ()
    score_threshold_bias: str = "conservative"
    notes: tuple[str, ...] = ()


class ResearchTuningEngine:
    """Loads and exposes small, symbol-aware trading adjustments."""

    def __init__(self, symbols: dict[str, SymbolResearchTuning] | None = None) -> None:
        self._symbols = symbols or {}

    @classmethod
    def from_json_file(cls, path: str | Path) -> "ResearchTuningEngine":
        """Load a tuning export generated by the research CLI."""

        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls.from_payload(payload)

    @classmethod
    def from_payload(cls, payload: dict[str, object]) -> "ResearchTuningEngine":
        """Build an engine from an already-parsed tuning payload."""

        symbols_payload = payload.get("symbols", {})
        symbols: dict[str, SymbolResearchTuning] = {}
        if isinstance(symbols_payload, dict):
            for symbol, raw in symbols_payload.items():
                if not isinstance(raw, dict):
                    continue
                symbols[str(symbol).upper()] = SymbolResearchTuning(
                    preferred_sessions=tuple(cls._normalize_session(name) for name in raw.get("preferred_sessions", [])),
                    avoided_sessions=tuple(cls._normalize_session(name) for name in raw.get("avoided_sessions", [])),
                    preferred_patterns=tuple(str(name) for name in raw.get("preferred_patterns", [])),
                    score_threshold_bias=str(raw.get("score_threshold_bias", "conservative")),
                    notes=tuple(str(note) for note in raw.get("notes", [])),
                )
        return cls(symbols=symbols)

    def tuning_for(self, symbol: str) -> SymbolResearchTuning:
        """Return tuning for a symbol, or an empty tuning object."""

        return self._symbols.get(symbol.upper(), SymbolResearchTuning())

    def minimum_score(self, symbol: str, base_score: int) -> int:
        """Raise threshold when research recommends stricter selection."""

        tuning = self.tuning_for(symbol)
        if tuning.score_threshold_bias == "raise":
            return base_score + 1
        return base_score

    def session_penalty(self, symbol: str, active_session: str | None) -> int:
        """Penalize sessions that research marked as weak for the symbol."""

        if not active_session:
            return 0
        tuning = self.tuning_for(symbol)
        normalized = self._normalize_session(active_session)
        return 1 if normalized in tuning.avoided_sessions else 0

    def allowed_strategies(self, symbol: str) -> tuple[StrategyType, ...]:
        """Map preferred pattern families to strategy families."""

        tuning = self.tuning_for(symbol)
        patterns = set(tuning.preferred_patterns)
        allowed: list[StrategyType] = []
        if patterns & REVERSAL_PATTERNS:
            allowed.append(StrategyType.LIQUIDITY_SWEEP_REVERSAL)
        if patterns & BREAKOUT_PATTERNS:
            allowed.append(StrategyType.BREAKOUT_RETEST)
        return tuple(dict.fromkeys(allowed))

    def strategy_allowed(self, symbol: str, strategy_type: StrategyType | None) -> bool:
        """Return whether research permits a strategy family for the symbol."""

        if strategy_type is None:
            return True
        allowed = self.allowed_strategies(symbol)
        if not allowed:
            return True
        return strategy_type in allowed

    def strategy_reason(self, symbol: str, strategy_type: StrategyType | None) -> str:
        """Explain why a strategy was filtered out by research."""

        if self.strategy_allowed(symbol, strategy_type):
            return ""
        allowed = ", ".join(item.value for item in self.allowed_strategies(symbol))
        return f"research tuning allows: {allowed}"

    @staticmethod
    def _normalize_session(name: str) -> str:
        normalized = str(name).strip().lower()
        if normalized.endswith("_open"):
            return normalized.replace("_open", "")
        return normalized
