"""Monitoring dashboard, alerts, and remote-control services."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from trading_robot.backtesting.stats import TradeRecord
from trading_robot.journal.logger import TradingLogger
from trading_robot.state import RobotState
from trading_robot.types.models import AccountSnapshot


@dataclass
class ControlState:
    """Mutable runtime controls for pausing, risk overrides, and symbol access."""

    paused: bool = False
    risk_override_pct: Decimal | None = None
    disabled_symbols: set[str] = field(default_factory=set)


@dataclass(frozen=True)
class ControlDecision:
    """Trade permission generated by the control layer."""

    trading_allowed: bool
    reason: str = ""
    risk_override_pct: Decimal | None = None


@dataclass(frozen=True)
class DashboardPosition:
    """Open-position row for the dashboard."""

    symbol: str
    entry_price: Decimal
    stop_loss: Decimal | None
    take_profit: Decimal | None
    current_profit: Decimal


@dataclass(frozen=True)
class DashboardSnapshot:
    """Real-time monitoring snapshot."""

    account_balance: Decimal
    daily_pnl: Decimal
    total_trades: int
    win_loss_ratio: Decimal
    drawdown: Decimal
    open_positions: tuple[DashboardPosition, ...]


@dataclass(frozen=True)
class CommandResult:
    """Result of one remote-control command."""

    success: bool
    message: str
    payload: dict[str, Any] = field(default_factory=dict)


class OperationsLogStore:
    """Append-only log for alerts sent and commands received."""

    def __init__(self, path: str | Path) -> None:
        self._path = Path(path)

    def record(self, event_type: str, payload: dict[str, Any]) -> None:
        """Persist one operations event."""

        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as handle:
            handle.write(
                json.dumps(
                    {
                        "timestamp": datetime.utcnow().isoformat(),
                        "event_type": event_type,
                        "payload": self._serialize(payload),
                    },
                    sort_keys=True,
                )
                + "\n"
            )

    def _serialize(self, payload: dict[str, Any]) -> dict[str, Any]:
        serialized: dict[str, Any] = {}
        for key, value in payload.items():
            if isinstance(value, Decimal):
                serialized[key] = str(value)
            elif isinstance(value, set):
                serialized[key] = sorted(value)
            elif isinstance(value, tuple):
                serialized[key] = list(value)
            else:
                serialized[key] = value
        return serialized


class DashboardService:
    """Builds lightweight dashboard snapshots from current state and trades."""

    def build_snapshot(
        self,
        account: AccountSnapshot,
        state: RobotState,
        trades: tuple[TradeRecord, ...] = (),
        prices_by_symbol: dict[str, Decimal] | None = None,
    ) -> DashboardSnapshot:
        """Return current dashboard values."""

        wins = sum(1 for trade in trades if trade.pnl > 0)
        losses = sum(1 for trade in trades if trade.pnl < 0)
        ratio = Decimal(wins) / Decimal(losses) if losses > 0 else (Decimal(wins) if wins > 0 else Decimal("0"))
        drawdown = abs(min(state.daily_pnl, Decimal("0")))
        positions = tuple(
            DashboardPosition(
                symbol=position.symbol,
                entry_price=position.entry_price,
                stop_loss=position.stop_loss,
                take_profit=position.take_profit,
                current_profit=self._current_profit(position, prices_by_symbol or {}),
            )
            for position in state.open_positions.values()
        )
        return DashboardSnapshot(
            account_balance=account.balance,
            daily_pnl=state.daily_pnl,
            total_trades=len(trades),
            win_loss_ratio=ratio,
            drawdown=drawdown,
            open_positions=positions,
        )

    def _current_profit(self, position, prices_by_symbol: dict[str, Decimal]) -> Decimal:
        current_price = prices_by_symbol.get(position.symbol, position.entry_price)
        if position.side.value == "buy":
            return (current_price - position.entry_price) * position.volume
        return (position.entry_price - current_price) * position.volume


class ControlCenter:
    """Handles remote commands and emits centralized control decisions."""

    def __init__(
        self,
        logger: TradingLogger | None = None,
        log_store: OperationsLogStore | None = None,
        dashboard_service: DashboardService | None = None,
    ) -> None:
        self._logger = logger or TradingLogger()
        self._log_store = log_store
        self._dashboard = dashboard_service or DashboardService()
        self._state = ControlState()

    @property
    def state(self) -> ControlState:
        """Return mutable control state."""

        return self._state

    def control_decision(self, symbol: str) -> ControlDecision:
        """Return current control permission for the symbol."""

        normalized = symbol.upper()
        if self._state.paused:
            return ControlDecision(False, "trading paused by operator", self._state.risk_override_pct)
        if normalized in self._state.disabled_symbols:
            return ControlDecision(False, f"symbol disabled: {normalized}", self._state.risk_override_pct)
        return ControlDecision(True, "control layer clear", self._state.risk_override_pct)

    def pause(self) -> CommandResult:
        self._state.paused = True
        return self._record_command("pause", CommandResult(True, "trading paused"))

    def resume(self) -> CommandResult:
        self._state.paused = False
        return self._record_command("resume", CommandResult(True, "trading resumed"))

    def set_risk_percent(self, risk_percent: Decimal) -> CommandResult:
        risk_pct = risk_percent / Decimal("100") if risk_percent > Decimal("1") else risk_percent / Decimal("100")
        self._state.risk_override_pct = risk_pct
        return self._record_command(
            "risk",
            CommandResult(True, f"risk override set to {risk_percent}%", {"risk_override_pct": risk_pct}),
        )

    def enable_symbol(self, symbol: str) -> CommandResult:
        normalized = symbol.upper()
        self._state.disabled_symbols.discard(normalized)
        return self._record_command("enable_symbol", CommandResult(True, f"symbol enabled: {normalized}"))

    def disable_symbol(self, symbol: str) -> CommandResult:
        normalized = symbol.upper()
        self._state.disabled_symbols.add(normalized)
        return self._record_command("disable_symbol", CommandResult(True, f"symbol disabled: {normalized}"))

    def status(
        self,
        account: AccountSnapshot | None = None,
        robot_state: RobotState | None = None,
        trades: tuple[TradeRecord, ...] = (),
        prices_by_symbol: dict[str, Decimal] | None = None,
    ) -> CommandResult:
        """Return current control and dashboard status."""

        payload: dict[str, Any] = {
            "paused": self._state.paused,
            "risk_override_pct": self._state.risk_override_pct,
            "disabled_symbols": tuple(sorted(self._state.disabled_symbols)),
        }
        if account is not None and robot_state is not None:
            payload["dashboard"] = self._dashboard.build_snapshot(
                account=account,
                state=robot_state,
                trades=trades,
                prices_by_symbol=prices_by_symbol,
            )
        result = CommandResult(True, "status generated", payload)
        return self._record_command("status", result)

    def process_command(
        self,
        command: str,
        account: AccountSnapshot | None = None,
        robot_state: RobotState | None = None,
        trades: tuple[TradeRecord, ...] = (),
        prices_by_symbol: dict[str, Decimal] | None = None,
    ) -> CommandResult:
        """Process chat-style operator commands."""

        parts = command.strip().split()
        if not parts:
            return self._record_command("unknown", CommandResult(False, "empty command"))

        action = parts[0].lower()
        if action == "/pause":
            return self.pause()
        if action == "/resume":
            return self.resume()
        if action == "/status":
            return self.status(account=account, robot_state=robot_state, trades=trades, prices_by_symbol=prices_by_symbol)
        if action == "/risk" and len(parts) == 2:
            return self.set_risk_percent(Decimal(parts[1]))
        if action == "/disable" and len(parts) == 2:
            return self.disable_symbol(parts[1])
        if action == "/enable" and len(parts) == 2:
            return self.enable_symbol(parts[1])
        return self._record_command(action, CommandResult(False, f"unsupported command: {command}"))

    def _record_command(self, command_name: str, result: CommandResult) -> CommandResult:
        payload = {"command": command_name, "success": result.success, "result_message": result.message, **result.payload}
        self._logger.info("control command processed", **payload)
        if self._log_store is not None:
            self._log_store.record("command_received", payload)
        return result

    def Pause(self) -> CommandResult:
        return self.pause()

    def Resume(self) -> CommandResult:
        return self.resume()

    def Status(
        self,
        account: AccountSnapshot | None = None,
        robot_state: RobotState | None = None,
        trades: tuple[TradeRecord, ...] = (),
        prices_by_symbol: dict[str, Decimal] | None = None,
    ) -> CommandResult:
        return self.status(account=account, robot_state=robot_state, trades=trades, prices_by_symbol=prices_by_symbol)

    def ProcessCommand(
        self,
        command: str,
        account: AccountSnapshot | None = None,
        robot_state: RobotState | None = None,
        trades: tuple[TradeRecord, ...] = (),
        prices_by_symbol: dict[str, Decimal] | None = None,
    ) -> CommandResult:
        return self.process_command(
            command=command,
            account=account,
            robot_state=robot_state,
            trades=trades,
            prices_by_symbol=prices_by_symbol,
        )
